# -*- coding: utf-8 -*-
"""Ejercicios curados en español.

Cada entrada: (id, id_free_exercise_db | None, nombre, patrón, músculos primarios, secundarios,
equipo, nivel, contraindicaciones, compuesto, unilateral, por_tiempo, pasos[3], consejo)

Patrones: HP empuje horizontal, VP empuje vertical, HL tracción horizontal, VL tracción vertical,
SQ sentadilla, HI bisagra, LU zancada/unilateral, CO core, IS aislamiento, CA transporte, CD cardio.
"""

P = {
    "HP": "HORIZONTAL_PUSH", "VP": "VERTICAL_PUSH", "HL": "HORIZONTAL_PULL", "VL": "VERTICAL_PULL",
    "SQ": "SQUAT", "HI": "HINGE", "LU": "LUNGE", "CO": "CORE", "IS": "ISOLATION", "CA": "CARRY",
    "CD": "CARDIO", "MO": "MOBILITY",
}
M = {
    "pecho": "CHEST", "dorsal": "LATS", "esp_media": "MIDDLE_BACK", "esp_baja": "LOWER_BACK",
    "trapecio": "TRAPS", "hombro": "SHOULDERS", "biceps": "BICEPS", "triceps": "TRICEPS",
    "antebrazo": "FOREARMS", "cuad": "QUADS", "isquio": "HAMSTRINGS", "gluteo": "GLUTES",
    "pantorrilla": "CALVES", "aductor": "ADDUCTORS", "abductor": "ABDUCTORS", "abdomen": "ABS",
    "cardio": "CARDIO",
}
E = {
    "cuerpo": "NONE", "manc": "DUMBBELL", "barra": "BARBELL", "barraz": "EZ_BAR", "rusa": "KETTLEBELL",
    "maquina": "MACHINE", "polea": "CABLE", "banda": "BANDS", "banco": "BENCH", "dominadas": "PULLUP_BAR",
    "bici": "BIKE", "cinta": "TREADMILL", "otro": "OTHER",
}
L = {"P": "BEGINNER", "I": "INTERMEDIATE", "A": "ADVANCED"}
Z = {
    "hombro": "SHOULDER", "rodilla": "KNEE", "lumbar": "LOWER_BACK", "muneca": "WRIST", "codo": "ELBOW",
    "cuello": "NECK", "tobillo": "ANKLE", "cadera": "HIP",
}

EJERCICIOS = [
    # ---------------- Imagen de referencia (rutina con pesas de 10 lb) ----------------
    ("sentadilla-goblet", "Goblet_Squat", "Sentadilla goblet", "SQ", "cuad gluteo", "abdomen aductor", "manc", "P", "rodilla", 1, 0, 0,
     ["Sostén la pesa frente al pecho con ambas manos.", "Baja como si te sentaras, rodillas en dirección de la punta de los pies.", "Sube empujando el piso con todo el pie."],
     "Mantén el pecho alto y los talones apoyados."),
    ("remo-una-mano", "One-Arm_Dumbbell_Row", "Remo a una mano", "HL", "dorsal esp_media", "biceps trapecio", "manc", "P", "lumbar", 1, 1, 0,
     ["Apoya la mano libre en una silla, mesa o banco.", "Espalda recta, deja colgar la pesa.", "Lleva la pesa hacia la cadera y baja lento."],
     "Piensa en llevar el codo atrás, no en subir la mano."),
    ("press-pecho-suelo", "Dumbbell_Floor_Press", "Press de pecho en el suelo", "HP", "pecho triceps", "hombro", "manc", "P", "", 1, 0, 0,
     ["Acostado boca arriba con rodillas dobladas.", "Pesas a la altura del pecho, codos a 45°.", "Empuja la pesa hacia arriba y baja hasta tocar el suelo con los codos."],
     "Ideal si el hombro molesta con el press tradicional."),
    ("peso-muerto-rumano-mancuernas", "Stiff-Legged_Dumbbell_Deadlift", "Peso muerto rumano con mancuernas", "HI", "isquio gluteo", "esp_baja", "manc", "P", "lumbar", 1, 0, 0,
     ["De pie con las pesas frente a los muslos.", "Lleva la cadera hacia atrás con rodillas levemente dobladas.", "Baja hasta sentir estiramiento atrás del muslo y vuelve apretando glúteos."],
     "Mantén la espalda neutra: la cadera se mueve, la espalda no se curva."),
    ("press-hombro-una-mano", "Dumbbell_One-Arm_Shoulder_Press", "Press de hombro a una mano", "VP", "hombro", "triceps abdomen", "manc", "P", "hombro", 1, 1, 0,
     ["De pie, pesa a la altura del hombro.", "Aprieta abdomen y glúteos.", "Empuja la pesa por encima de la cabeza con control y baja lento."],
     "No arquees la espalda baja para empujar."),
    ("curl-biceps-mancuerna", "Dumbbell_Bicep_Curl", "Curl de bíceps con mancuernas", "IS", "biceps", "antebrazo", "manc", "P", "codo", 0, 0, 0,
     ["De pie con brazos extendidos y palmas al frente.", "Sube la pesa doblando el codo sin mover el hombro.", "Baja lento hasta extender el brazo."],
     "Sin balancearte: si necesitas impulso, baja el peso."),
    ("puente-gluteos", "Butt_Lift_Bridge", "Puente de glúteos", "HI", "gluteo", "isquio", "cuerpo", "P", "", 0, 0, 0,
     ["Acostado boca arriba, rodillas dobladas y pies apoyados.", "Eleva la cadera apretando glúteos.", "Sostén un segundo arriba y baja lento."],
     "Puede ser sin peso o con una pesa sobre la cadera."),
    ("plancha-elevada", None, "Plancha elevada", "CO", "abdomen", "hombro gluteo", "cuerpo", "P", "", 0, 0, 1,
     ["Apoya las manos en una mesa, banco o sofá.", "Cuerpo recto de cabeza a talones.", "Aprieta abdomen y glúteos y sostén el tiempo indicado."],
     "Versión más fácil de la plancha; cuanto más alto el apoyo, más fácil."),

    # ---------------- Pierna: sentadilla ----------------
    ("sentadilla-barra", "Barbell_Squat", "Sentadilla con barra", "SQ", "cuad gluteo", "isquio esp_baja", "barra", "I", "rodilla lumbar", 1, 0, 0,
     ["Barra sobre los trapecios, pies al ancho de hombros.", "Baja controlado hasta que el muslo quede paralelo al piso.", "Sube empujando con todo el pie y el pecho alto."],
     "Rodillas siguen la dirección de los pies."),
    ("sentadilla-frontal", "Front_Barbell_Squat", "Sentadilla frontal", "SQ", "cuad", "gluteo abdomen", "barra", "A", "rodilla muneca", 1, 0, 0,
     ["Barra apoyada al frente de los hombros, codos altos.", "Baja con el torso vertical.", "Sube sin dejar caer los codos."],
     "Requiere buena movilidad de muñeca y tobillo."),
    ("sentadilla-peso-corporal", "Bodyweight_Squat", "Sentadilla sin peso", "SQ", "cuad gluteo", "", "cuerpo", "P", "rodilla", 1, 0, 0,
     ["Pies al ancho de hombros, brazos al frente.", "Baja llevando la cadera atrás.", "Sube apretando glúteos."],
     "Buena para calentar o para empezar."),
    ("sentadilla-a-silla", "Chair_Squat", "Sentadilla a silla", "SQ", "cuad gluteo", "", "cuerpo", "P", "", 1, 0, 0,
     ["Párate frente a una silla.", "Baja hasta rozar el asiento sin dejarte caer.", "Sube empujando con los talones."],
     "Regresión segura si la sentadilla libre cuesta."),
    ("sentadilla-mancuernas", "Dumbbell_Squat", "Sentadilla con mancuernas", "SQ", "cuad gluteo", "isquio", "manc", "P", "rodilla", 1, 0, 0,
     ["Una mancuerna en cada mano a los costados.", "Baja con la espalda recta.", "Sube empujando el piso."],
     None),
    ("prensa-piernas", "Leg_Press", "Prensa de piernas", "SQ", "cuad gluteo", "isquio", "maquina", "P", "", 1, 0, 0,
     ["Siéntate con la espalda apoyada y pies al ancho de hombros.", "Baja la plataforma hasta 90° de rodilla.", "Empuja sin bloquear las rodillas."],
     "No despegues la espalda baja del respaldo."),
    ("hack-squat", "Hack_Squat", "Sentadilla hack", "SQ", "cuad", "gluteo", "maquina", "I", "rodilla", 1, 0, 0,
     ["Espalda apoyada en la máquina.", "Baja controlado.", "Sube sin bloquear rodillas."], None),
    ("sentadilla-smith", "Smith_Machine_Squat", "Sentadilla en máquina Smith", "SQ", "cuad gluteo", "", "maquina", "P", "rodilla", 1, 0, 0,
     ["Barra guiada sobre los trapecios.", "Pies un poco adelante.", "Baja y sube con control."], None),
    ("sentadilla-caja", "Box_Squat", "Sentadilla a cajón", "SQ", "cuad gluteo", "isquio", "barra banco", "I", "rodilla", 1, 0, 0,
     ["Coloca un banco o cajón detrás.", "Baja hasta sentarte brevemente.", "Sube explosivo sin rebotar."], None),
    ("sentadilla-sumo-mancuerna", "Plie_Dumbbell_Squat", "Sentadilla sumo con mancuerna", "SQ", "aductor gluteo cuad", "", "manc", "P", "cadera", 1, 0, 0,
     ["Pies más abiertos que los hombros, puntas afuera.", "Sostén una mancuerna entre las piernas.", "Baja recto y sube apretando glúteos."], None),
    ("sentadilla-con-salto", "Freehand_Jump_Squat", "Sentadilla con salto", "SQ", "cuad gluteo", "pantorrilla", "cuerpo", "I", "rodilla tobillo", 1, 0, 0,
     ["Baja a sentadilla.", "Salta explosivo.", "Aterriza suave y repite."], None),

    # ---------------- Pierna: zancadas / unilateral ----------------
    ("zancada-mancuernas", "Dumbbell_Lunges", "Zancadas con mancuernas", "LU", "cuad gluteo", "isquio", "manc", "P", "rodilla", 1, 1, 0,
     ["Da un paso largo al frente.", "Baja hasta que la rodilla trasera casi toque el piso.", "Vuelve empujando con el pie delantero."], None),
    ("zancada-atras", "Dumbbell_Rear_Lunge", "Zancada hacia atrás", "LU", "cuad gluteo", "isquio", "manc", "P", "", 1, 1, 0,
     ["De pie con pesas.", "Da un paso atrás y baja.", "Vuelve a la posición inicial."], "Más amable con la rodilla que la zancada al frente."),
    ("zancada-caminando", "Bodyweight_Walking_Lunge", "Zancadas caminando", "LU", "cuad gluteo", "", "cuerpo", "P", "rodilla", 1, 1, 0,
     ["Avanza dando pasos largos.", "Baja la rodilla trasera cerca del piso.", "Alterna piernas."], None),
    ("sentadilla-bulgara", "Split_Squat_with_Dumbbells", "Sentadilla búlgara / split squat", "LU", "cuad gluteo", "", "manc", "I", "rodilla", 1, 1, 0,
     ["Pie trasero apoyado atrás (o en un banco).", "Baja recto con el torso firme.", "Sube empujando con la pierna delantera."], None),
    ("subida-cajon", "Dumbbell_Step_Ups", "Subida al cajón", "LU", "cuad gluteo", "", "manc banco", "P", "", 1, 1, 0,
     ["Pie completo sobre un banco o escalón.", "Sube empujando con esa pierna.", "Baja controlado."], None),
    ("zancada-barra", "Barbell_Lunge", "Zancadas con barra", "LU", "cuad gluteo", "", "barra", "I", "rodilla", 1, 1, 0,
     ["Barra sobre los trapecios.", "Paso al frente y baja.", "Vuelve empujando."], None),

    # ---------------- Pierna: bisagra ----------------
    ("peso-muerto-barra", "Barbell_Deadlift", "Peso muerto con barra", "HI", "isquio gluteo esp_baja", "trapecio antebrazo cuad", "barra", "I", "lumbar", 1, 0, 0,
     ["Barra sobre la mitad del pie, agárrala con espalda neutra.", "Empuja el piso y extiende cadera y rodillas a la vez.", "Baja la barra pegada a las piernas."],
     "Nunca redondees la espalda baja."),
    ("peso-muerto-rumano-barra", "Romanian_Deadlift", "Peso muerto rumano con barra", "HI", "isquio gluteo", "esp_baja", "barra", "I", "lumbar", 1, 0, 0,
     ["De pie con la barra frente a los muslos.", "Lleva la cadera atrás deslizando la barra por las piernas.", "Vuelve apretando glúteos."], None),
    ("peso-muerto-sumo", "Sumo_Deadlift", "Peso muerto sumo", "HI", "gluteo aductor isquio", "cuad esp_baja", "barra", "I", "lumbar cadera", 1, 0, 0,
     ["Pies muy abiertos, manos por dentro de las piernas.", "Pecho alto, espalda neutra.", "Empuja el piso hacia afuera y sube."], None),
    ("peso-muerto-trap", "Trap_Bar_Deadlift", "Peso muerto con barra hexagonal", "HI", "cuad gluteo isquio", "esp_baja", "barra", "I", "lumbar", 1, 0, 0,
     ["Párate dentro de la barra.", "Agarra las manijas con espalda neutra.", "Empuja el piso y sube."], "Menos exigente para la espalda baja."),
    ("hip-thrust", "Barbell_Hip_Thrust", "Hip thrust", "HI", "gluteo", "isquio", "barra banco", "P", "", 1, 0, 0,
     ["Espalda alta apoyada en un banco, barra sobre la cadera.", "Empuja la cadera hacia arriba.", "Aprieta glúteos un segundo y baja."], None),
    ("puente-gluteo-barra", "Barbell_Glute_Bridge", "Puente de glúteo con barra", "HI", "gluteo", "isquio", "barra", "P", "", 1, 0, 0,
     ["Acostado en el piso con la barra sobre la cadera.", "Eleva la cadera.", "Baja lento."], None),
    ("puente-una-pierna", "Single_Leg_Glute_Bridge", "Puente de glúteo a una pierna", "HI", "gluteo", "isquio", "cuerpo", "P", "", 0, 1, 0,
     ["Acostado, una pierna extendida en el aire.", "Eleva la cadera con la otra.", "Baja controlado."], None),
    ("swing-rusa", "One-Arm_Kettlebell_Swings", "Swing con pesa rusa", "HI", "gluteo isquio", "esp_baja hombro", "rusa", "I", "lumbar", 1, 0, 0,
     ["Pies al ancho de hombros, pesa entre las piernas.", "Impulsa con la cadera, no con los brazos.", "Deja que la pesa baje y repite."], None),
    ("buenos-dias", "Good_Morning", "Buenos días con barra", "HI", "isquio esp_baja", "gluteo", "barra", "I", "lumbar", 1, 0, 0,
     ["Barra sobre los trapecios.", "Inclina el torso llevando la cadera atrás.", "Vuelve apretando glúteos."], None),
    ("hiperextensiones", "Hyperextensions_Back_Extensions", "Hiperextensiones", "HI", "esp_baja gluteo", "isquio", "maquina", "P", "lumbar", 0, 0, 0,
     ["Cadera apoyada en el banco de hiperextensiones.", "Baja el torso con espalda neutra.", "Sube hasta alinear el cuerpo."], None),
    ("peso-muerto-una-pierna", "Kettlebell_One-Legged_Deadlift", "Peso muerto a una pierna", "HI", "isquio gluteo", "", "rusa", "I", "tobillo", 1, 1, 0,
     ["Pesa en la mano contraria a la pierna de apoyo.", "Inclina el torso y lleva la pierna libre atrás.", "Vuelve con control."], None),
    ("pull-through-polea", "Pull_Through", "Pull-through en polea", "HI", "gluteo isquio", "", "polea", "P", "", 1, 0, 0,
     ["De espaldas a la polea baja, cuerda entre las piernas.", "Lleva la cadera atrás.", "Extiende la cadera apretando glúteos."], "Alternativa amable al peso muerto."),
    ("buenos-dias-banda", "Band_Good_Morning", "Buenos días con banda", "HI", "isquio gluteo", "esp_baja", "banda", "P", "", 1, 0, 0,
     ["Pisa la banda y pásala por detrás del cuello.", "Inclina el torso con la espalda neutra.", "Vuelve a la posición vertical."], None),

    # ---------------- Pierna: aislamiento ----------------
    ("extension-cuadriceps", "Leg_Extensions", "Extensión de cuádriceps", "IS", "cuad", "", "maquina", "P", "rodilla", 0, 0, 0,
     ["Siéntate con la almohadilla sobre los tobillos.", "Extiende las rodillas.", "Baja lento."], None),
    ("curl-femoral-acostado", "Lying_Leg_Curls", "Curl femoral acostado", "IS", "isquio", "", "maquina", "P", "", 0, 0, 0,
     ["Acostado boca abajo en la máquina.", "Lleva los talones hacia los glúteos.", "Baja controlado."], None),
    ("curl-femoral-sentado", "Seated_Leg_Curl", "Curl femoral sentado", "IS", "isquio", "", "maquina", "P", "", 0, 0, 0,
     ["Siéntate con la almohadilla detrás de los tobillos.", "Flexiona las rodillas.", "Vuelve lento."], None),
    ("curl-femoral-balon", "Ball_Leg_Curl", "Curl femoral con balón", "IS", "isquio", "gluteo", "otro", "P", "", 0, 0, 0,
     ["Acostado con talones sobre un balón suizo.", "Eleva la cadera y trae el balón hacia ti.", "Extiende lento."], None),
    ("curl-femoral-banda", "Seated_Band_Hamstring_Curl", "Curl femoral con banda", "IS", "isquio", "", "banda", "P", "", 0, 0, 0,
     ["Banda atada al frente y en los tobillos.", "Flexiona las rodillas contra la banda.", "Vuelve lento."], None),
    ("aductores-maquina", "Thigh_Adductor", "Aductores en máquina", "IS", "aductor", "", "maquina", "P", "cadera", 0, 0, 0,
     ["Siéntate con las almohadillas por dentro de las rodillas.", "Cierra las piernas.", "Abre lento."], None),
    ("abductores-maquina", "Thigh_Abductor", "Abductores en máquina", "IS", "abductor gluteo", "", "maquina", "P", "cadera", 0, 0, 0,
     ["Almohadillas por fuera de las rodillas.", "Abre las piernas.", "Cierra lento."], None),
    ("patada-gluteo", "Glute_Kickback", "Patada de glúteo", "IS", "gluteo", "isquio", "cuerpo", "P", "", 0, 1, 0,
     ["En cuatro apoyos.", "Lleva una pierna atrás y arriba.", "Baja sin arquear la espalda."], None),
    ("patada-gluteo-polea", "One-Legged_Cable_Kickback", "Patada de glúteo en polea", "IS", "gluteo", "", "polea", "P", "", 0, 1, 0,
     ["Tobillera en polea baja.", "Lleva la pierna atrás.", "Vuelve lento."], None),
    ("caminata-monstruo", "Monster_Walk", "Caminata lateral con banda", "IS", "abductor gluteo", "", "banda", "P", "", 0, 0, 0,
     ["Banda sobre las rodillas o tobillos.", "Semiflexiona las piernas.", "Da pasos laterales sin juntar los pies."], None),
    ("pantorrilla-pie", "Standing_Calf_Raises", "Elevación de pantorrillas de pie", "IS", "pantorrilla", "", "maquina", "P", "tobillo", 0, 0, 0,
     ["Hombros bajo las almohadillas, puntas en el borde.", "Sube en puntas de pie.", "Baja estirando."], None),
    ("pantorrilla-sentado", "Seated_Calf_Raise", "Elevación de pantorrillas sentado", "IS", "pantorrilla", "", "maquina", "P", "tobillo", 0, 0, 0,
     ["Sentado con almohadilla sobre los muslos.", "Sube los talones.", "Baja estirando."], None),
    ("pantorrilla-mancuerna", "Standing_Dumbbell_Calf_Raise", "Elevación de pantorrillas con mancuernas", "IS", "pantorrilla", "", "manc", "P", "tobillo", 0, 0, 0,
     ["Mancuernas a los costados, puntas en un escalón.", "Sube en puntas.", "Baja lento."], None),
    ("pantorrilla-prensa", "Calf_Press_On_The_Leg_Press_Machine", "Pantorrillas en prensa", "IS", "pantorrilla", "", "maquina", "P", "tobillo", 0, 0, 0,
     ["Puntas de los pies en el borde de la plataforma.", "Empuja con los tobillos.", "Vuelve estirando."], None),

    # ---------------- Pecho ----------------
    ("press-banca", "Barbell_Bench_Press_-_Medium_Grip", "Press de banca con barra", "HP", "pecho", "triceps hombro", "barra banco", "I", "hombro muneca", 1, 0, 0,
     ["Acostado, ojos bajo la barra, omóplatos juntos.", "Baja la barra a la parte baja del pecho.", "Empuja hasta extender los brazos."],
     "Usa ayudante o topes de seguridad."),
    ("press-inclinado-barra", "Barbell_Incline_Bench_Press_-_Medium_Grip", "Press inclinado con barra", "HP", "pecho hombro", "triceps", "barra banco", "I", "hombro", 1, 0, 0,
     ["Banco a 30–45°.", "Baja la barra a la parte alta del pecho.", "Empuja arriba."], None),
    ("press-banca-mancuernas", "Dumbbell_Bench_Press", "Press de banca con mancuernas", "HP", "pecho", "triceps hombro", "manc banco", "P", "hombro", 1, 0, 0,
     ["Acostado en el banco con mancuernas a los lados del pecho.", "Empuja hacia arriba juntándolas.", "Baja lento hasta sentir estiramiento."], None),
    ("press-neutro-mancuernas", "Dumbbell_Bench_Press_with_Neutral_Grip", "Press con mancuernas agarre neutro", "HP", "pecho triceps", "hombro", "manc banco", "P", "", 1, 0, 0,
     ["Palmas enfrentadas.", "Codos cerca del cuerpo.", "Empuja y baja lento."], "Más cómodo para hombros sensibles."),
    ("press-inclinado-mancuernas", "Incline_Dumbbell_Press", "Press inclinado con mancuernas", "HP", "pecho hombro", "triceps", "manc banco", "P", "hombro", 1, 0, 0,
     ["Banco inclinado.", "Mancuernas a la altura del pecho.", "Empuja arriba y baja lento."], None),
    ("press-pecho-maquina", "Leverage_Chest_Press", "Press de pecho en máquina", "HP", "pecho", "triceps hombro", "maquina", "P", "", 1, 0, 0,
     ["Ajusta el asiento: manijas a media altura del pecho.", "Empuja al frente.", "Vuelve sin chocar las placas."], None),
    ("press-smith", "Smith_Machine_Bench_Press", "Press de banca en Smith", "HP", "pecho", "triceps hombro", "maquina banco", "P", "hombro", 1, 0, 0,
     ["Banco bajo la barra guiada.", "Baja al pecho.", "Empuja."], None),
    ("press-polea-pie", "Standing_Cable_Chest_Press", "Press de pecho en polea de pie", "HP", "pecho", "triceps abdomen", "polea", "P", "", 1, 0, 0,
     ["De espaldas a las poleas.", "Empuja al frente con abdomen firme.", "Vuelve controlado."], None),
    ("aperturas-mancuernas", "Dumbbell_Flyes", "Aperturas con mancuernas", "IS", "pecho", "hombro", "manc banco", "P", "hombro", 0, 0, 0,
     ["Acostado, brazos arriba con codos levemente doblados.", "Abre los brazos en arco.", "Cierra apretando el pecho."], None),
    ("cruce-poleas", "Cable_Crossover", "Cruce de poleas", "IS", "pecho", "hombro", "polea", "P", "hombro", 0, 0, 0,
     ["Poleas altas, un pie adelante.", "Lleva las manos juntas al frente y abajo.", "Vuelve lento."], None),
    ("pec-deck", "Butterfly", "Aperturas en máquina (pec deck)", "IS", "pecho", "", "maquina", "P", "hombro", 0, 0, 0,
     ["Espalda apoyada, brazos en las almohadillas.", "Junta los brazos al frente.", "Abre lento."], None),
    ("flexiones", "Pushups", "Flexiones de brazos", "HP", "pecho triceps", "hombro abdomen", "cuerpo", "P", "muneca hombro", 1, 0, 0,
     ["Manos un poco más abiertas que los hombros.", "Cuerpo recto, baja el pecho al piso.", "Empuja hasta extender."], None),
    ("flexiones-inclinadas", "Incline_Push-Up", "Flexiones inclinadas", "HP", "pecho triceps", "hombro", "cuerpo", "P", "muneca", 1, 0, 0,
     ["Manos en una mesa, banco o pared.", "Cuerpo recto.", "Baja el pecho y empuja."], "Más fácil que la flexión en el piso."),
    ("flexiones-rodillas", None, "Flexiones con rodillas apoyadas", "HP", "pecho triceps", "hombro", "cuerpo", "P", "muneca", 1, 0, 0,
     ["Rodillas en el piso, cuerpo recto de rodillas a cabeza.", "Baja el pecho.", "Empuja."], None),
    ("flexiones-pies-elevados", "Push-Ups_With_Feet_Elevated", "Flexiones con pies elevados", "HP", "pecho hombro", "triceps", "cuerpo", "I", "muneca hombro", 1, 0, 0,
     ["Pies sobre un banco.", "Cuerpo recto.", "Baja y empuja."], None),
    ("fondos-pecho", "Dips_-_Chest_Version", "Fondos para pecho", "HP", "pecho triceps", "hombro", "otro", "I", "hombro codo", 1, 0, 0,
     ["En paralelas, torso inclinado adelante.", "Baja hasta 90° de codo.", "Empuja arriba."], None),
    ("press-banca-banda", "Bench_Press_-_With_Bands", "Press de pecho con banda", "HP", "pecho", "triceps", "banda", "P", "", 1, 0, 0,
     ["Banda por la espalda, un extremo en cada mano.", "Empuja al frente.", "Vuelve lento."], None),

    # ---------------- Espalda: tracción vertical ----------------
    ("dominadas", "Pullups", "Dominadas", "VL", "dorsal", "biceps esp_media", "dominadas", "I", "hombro codo", 1, 0, 0,
     ["Cuelga de la barra con agarre prono.", "Sube hasta pasar la barbilla sobre la barra.", "Baja controlado."], None),
    ("dominadas-supinas", "Chin-Up", "Dominadas supinas (chin-up)", "VL", "dorsal biceps", "", "dominadas", "I", "codo", 1, 0, 0,
     ["Palmas hacia ti.", "Sube el pecho a la barra.", "Baja lento."], None),
    ("dominadas-asistidas", "Band_Assisted_Pull-Up", "Dominadas asistidas con banda", "VL", "dorsal", "biceps", "dominadas banda", "P", "hombro", 1, 0, 0,
     ["Banda en la barra y bajo las rodillas o pies.", "Sube el pecho a la barra.", "Baja controlado."], None),
    ("jalon-pecho", "Wide-Grip_Lat_Pulldown", "Jalón al pecho", "VL", "dorsal", "biceps esp_media", "maquina", "P", "", 1, 0, 0,
     ["Siéntate con los muslos fijos.", "Lleva la barra a la parte alta del pecho.", "Sube lento estirando."], None),
    ("jalon-agarre-cerrado", "Close-Grip_Front_Lat_Pulldown", "Jalón agarre cerrado", "VL", "dorsal", "biceps", "maquina", "P", "", 1, 0, 0,
     ["Agarre estrecho.", "Tira hacia el pecho.", "Sube lento."], None),
    ("jalon-supino", "Underhand_Cable_Pulldowns", "Jalón supino", "VL", "dorsal biceps", "", "polea", "P", "", 1, 0, 0,
     ["Palmas hacia ti.", "Tira hacia el pecho.", "Sube controlado."], None),
    ("jalon-una-mano", "One_Arm_Lat_Pulldown", "Jalón a una mano", "VL", "dorsal", "biceps", "polea", "P", "", 1, 1, 0,
     ["Manija en polea alta.", "Tira hacia el costado del pecho.", "Sube estirando."], None),
    ("pullover-polea", "Rope_Straight-Arm_Pulldown", "Pullover en polea", "IS", "dorsal", "triceps", "polea", "P", "hombro", 0, 0, 0,
     ["Brazos casi rectos frente a ti.", "Lleva la cuerda hasta los muslos.", "Vuelve lento."], None),
    ("pullover-mancuerna", "Straight-Arm_Dumbbell_Pullover", "Pullover con mancuerna", "IS", "dorsal pecho", "triceps", "manc banco", "I", "hombro", 0, 0, 0,
     ["Acostado, mancuerna sobre el pecho.", "Llévala atrás de la cabeza con brazos casi rectos.", "Vuelve."], None),
    ("jalon-banda", None, "Jalón con banda", "VL", "dorsal", "biceps", "banda", "P", "", 1, 0, 0,
     ["Banda anclada arriba (puerta).", "Tira hacia el pecho.", "Sube lento."], None),

    # ---------------- Espalda: tracción horizontal ----------------
    ("remo-barra", "Bent_Over_Barbell_Row", "Remo con barra", "HL", "esp_media dorsal", "biceps esp_baja", "barra", "I", "lumbar", 1, 0, 0,
     ["Inclina el torso con espalda neutra.", "Lleva la barra al abdomen.", "Baja controlado."], None),
    ("remo-mancuernas", "Bent_Over_Two-Dumbbell_Row", "Remo con dos mancuernas", "HL", "esp_media dorsal", "biceps", "manc", "P", "lumbar", 1, 0, 0,
     ["Torso inclinado, mancuernas colgando.", "Lleva los codos atrás.", "Baja lento."], None),
    ("remo-apoyado", "Dumbbell_Incline_Row", "Remo con pecho apoyado", "HL", "esp_media dorsal", "biceps", "manc banco", "P", "", 1, 0, 0,
     ["Pecho apoyado en banco inclinado.", "Lleva las mancuernas hacia atrás.", "Baja lento."], "Sin carga en la espalda baja."),
    ("remo-polea-sentado", "Seated_Cable_Rows", "Remo en polea sentado", "HL", "esp_media dorsal", "biceps", "polea", "P", "", 1, 0, 0,
     ["Sentado, espalda recta.", "Lleva la manija al abdomen juntando omóplatos.", "Vuelve estirando."], None),
    ("remo-maquina", "Leverage_Iso_Row", "Remo en máquina", "HL", "esp_media dorsal", "biceps", "maquina", "P", "", 1, 0, 0,
     ["Pecho apoyado en el respaldo.", "Tira de las manijas.", "Vuelve lento."], None),
    ("remo-t", "T-Bar_Row_with_Handle", "Remo en T", "HL", "esp_media dorsal", "biceps", "barra", "I", "lumbar", 1, 0, 0,
     ["Torso inclinado sobre la barra.", "Tira hacia el pecho.", "Baja lento."], None),
    ("remo-invertido", "Inverted_Row", "Remo invertido", "HL", "esp_media dorsal", "biceps", "barra", "P", "", 1, 0, 0,
     ["Cuelga bajo una barra baja o mesa firme.", "Cuerpo recto, tira el pecho hacia la barra.", "Baja lento."], None),
    ("remo-banda", None, "Remo con banda", "HL", "esp_media dorsal", "biceps", "banda", "P", "", 1, 0, 0,
     ["Banda anclada al frente.", "Tira llevando codos atrás.", "Vuelve lento."], None),
    ("remo-bajo-mesa", None, "Remo bajo una mesa", "HL", "esp_media dorsal", "biceps", "cuerpo", "P", "", 1, 0, 0,
     ["Acuéstate bajo una mesa firme y agarra el borde.", "Con el cuerpo recto, tira del pecho hacia la mesa.", "Baja lento. Verifica antes que la mesa no se vuelque."],
     "Cuanto más dobladas las rodillas, más fácil."),
    ("ytw-piso", None, "Y-T-W boca abajo", "HL", "hombro esp_media", "trapecio esp_baja", "cuerpo", "P", "", 0, 0, 0,
     ["Boca abajo, brazos estirados al frente formando una Y.", "Eleva los brazos del piso; luego haz lo mismo en T y en W.", "Baja lento; una letra de cada = 1 repetición."],
     "Excelente para la postura y la salud del hombro."),
    ("superman", None, "Superman", "HI", "esp_baja gluteo", "hombro", "cuerpo", "P", "", 0, 0, 0,
     ["Boca abajo con brazos estirados al frente.", "Eleva a la vez brazos, pecho y piernas.", "Sostén 2 segundos y baja."], None),
    ("face-pull", "Face_Pull", "Face pull", "HL", "hombro esp_media", "trapecio", "polea", "P", "", 0, 0, 0,
     ["Cuerda en polea alta.", "Tira hacia la cara separando las manos.", "Vuelve lento."], "Excelente para la salud del hombro."),
    ("separacion-banda", "Band_Pull_Apart", "Separación de banda", "HL", "hombro esp_media", "trapecio", "banda", "P", "", 0, 0, 0,
     ["Banda al frente con brazos extendidos.", "Sepárala llevando las manos a los lados.", "Vuelve lento."], None),
    ("remo-rusa", "One-Arm_Kettlebell_Row", "Remo con pesa rusa", "HL", "esp_media dorsal", "biceps", "rusa", "P", "lumbar", 1, 1, 0,
     ["Apoya una mano y rodilla.", "Tira de la pesa.", "Baja lento."], None),

    # ---------------- Hombros ----------------
    ("press-militar", "Standing_Military_Press", "Press militar con barra", "VP", "hombro", "triceps trapecio", "barra", "I", "hombro lumbar", 1, 0, 0,
     ["De pie, barra frente a los hombros.", "Empuja por encima de la cabeza.", "Baja controlado."], None),
    ("press-hombro-mancuernas", "Dumbbell_Shoulder_Press", "Press de hombro con mancuernas", "VP", "hombro", "triceps", "manc", "P", "hombro", 1, 0, 0,
     ["Sentado o de pie, mancuernas a la altura de las orejas.", "Empuja arriba.", "Baja lento."], None),
    ("press-arnold", "Arnold_Dumbbell_Press", "Press Arnold", "VP", "hombro", "triceps", "manc", "I", "hombro", 1, 0, 0,
     ["Palmas hacia ti frente a la cara.", "Gira las palmas al empujar arriba.", "Vuelve girando."], None),
    ("press-hombro-maquina", "Machine_Shoulder_Military_Press", "Press de hombro en máquina", "VP", "hombro", "triceps", "maquina", "P", "", 1, 0, 0,
     ["Ajusta el asiento.", "Empuja arriba.", "Baja controlado."], None),
    ("press-landmine", None, "Press landmine", "VP", "hombro pecho", "triceps abdomen", "barra", "P", "", 1, 1, 0,
     ["Un extremo de la barra anclado en una esquina.", "Empuja el otro extremo arriba y al frente.", "Baja controlado."],
     "Ángulo amable para hombros con molestias."),
    ("press-hombro-banda", "Shoulder_Press_-_With_Bands", "Press de hombro con banda", "VP", "hombro", "triceps", "banda", "P", "", 1, 0, 0,
     ["Pisa la banda, manos a los hombros.", "Empuja arriba.", "Baja lento."], None),
    ("flexion-pica", None, "Flexión en pica", "VP", "hombro triceps", "", "cuerpo", "I", "muneca hombro", 1, 0, 0,
     ["Cadera alta formando una V invertida.", "Baja la cabeza hacia el piso doblando codos.", "Empuja arriba."], None),
    ("elevaciones-laterales", "Side_Lateral_Raise", "Elevaciones laterales", "IS", "hombro", "", "manc", "P", "hombro", 0, 0, 0,
     ["De pie, mancuernas a los costados.", "Sube los brazos a los lados hasta la altura del hombro.", "Baja lento."], None),
    ("elevaciones-laterales-polea", "Cable_Seated_Lateral_Raise", "Elevación lateral en polea", "IS", "hombro", "", "polea", "P", "hombro", 0, 1, 0,
     ["Polea baja al costado.", "Sube el brazo lateralmente.", "Baja lento."], None),
    ("elevaciones-laterales-banda", "Lateral_Raise_-_With_Bands", "Elevaciones laterales con banda", "IS", "hombro", "", "banda", "P", "", 0, 0, 0,
     ["Pisa la banda.", "Sube los brazos a los lados.", "Baja lento."], None),
    ("elevaciones-frontales", "Front_Dumbbell_Raise", "Elevaciones frontales", "IS", "hombro", "", "manc", "P", "hombro", 0, 0, 0,
     ["Mancuernas frente a los muslos.", "Sube al frente hasta la altura del hombro.", "Baja lento."], None),
    ("pajaros", "Seated_Bent-Over_Rear_Delt_Raise", "Pájaros (deltoide posterior)", "IS", "hombro", "esp_media", "manc", "P", "", 0, 0, 0,
     ["Torso inclinado.", "Abre los brazos a los lados.", "Baja lento."], None),
    ("posterior-maquina", "Reverse_Machine_Flyes", "Deltoide posterior en máquina", "IS", "hombro", "esp_media", "maquina", "P", "", 0, 0, 0,
     ["Pecho contra el respaldo.", "Abre los brazos atrás.", "Vuelve lento."], None),
    ("encogimientos", "Dumbbell_Shrug", "Encogimientos de hombros", "IS", "trapecio", "", "manc", "P", "cuello", 0, 0, 0,
     ["Mancuernas a los costados.", "Sube los hombros hacia las orejas.", "Baja lento."], None),
    ("rotacion-externa-banda", "External_Rotation_with_Band", "Rotación externa con banda", "IS", "hombro", "", "banda", "P", "", 0, 1, 0,
     ["Codo pegado al cuerpo a 90°.", "Gira el antebrazo hacia afuera.", "Vuelve lento."], "Prevención de lesiones de hombro."),

    # ---------------- Brazos ----------------
    ("curl-barra", "Barbell_Curl", "Curl con barra", "IS", "biceps", "antebrazo", "barra", "P", "codo muneca", 0, 0, 0,
     ["De pie, barra con palmas al frente.", "Sube doblando codos.", "Baja lento."], None),
    ("curl-barra-z", "EZ-Bar_Curl", "Curl con barra Z", "IS", "biceps", "antebrazo", "barraz", "P", "codo", 0, 0, 0,
     ["Agarra la barra Z en la parte angulada.", "Sube.", "Baja lento."], "Más cómodo para las muñecas."),
    ("curl-martillo", "Hammer_Curls", "Curl martillo", "IS", "biceps antebrazo", "", "manc", "P", "", 0, 0, 0,
     ["Palmas enfrentadas.", "Sube sin girar la muñeca.", "Baja lento."], None),
    ("curl-inclinado", "Incline_Dumbbell_Curl", "Curl inclinado", "IS", "biceps", "", "manc banco", "I", "hombro", 0, 0, 0,
     ["Sentado en banco inclinado, brazos colgando.", "Sube las mancuernas.", "Baja lento."], None),
    ("curl-concentrado", "Concentration_Curls", "Curl concentrado", "IS", "biceps", "", "manc", "P", "", 0, 1, 0,
     ["Sentado, codo apoyado en el muslo.", "Sube la mancuerna.", "Baja lento."], None),
    ("curl-polea", "Standing_Biceps_Cable_Curl", "Curl en polea", "IS", "biceps", "", "polea", "P", "", 0, 0, 0,
     ["Barra en polea baja.", "Sube doblando codos.", "Baja lento."], None),
    ("curl-predicador", "Preacher_Curl", "Curl predicador", "IS", "biceps", "", "barraz banco", "P", "codo", 0, 0, 0,
     ["Brazos apoyados en el banco Scott.", "Sube.", "Baja sin extender bruscamente."], None),
    ("curl-banda", None, "Curl con banda", "IS", "biceps", "", "banda", "P", "", 0, 0, 0,
     ["Pisa la banda.", "Sube doblando codos.", "Baja lento."], None),
    ("extension-triceps-polea", "Triceps_Pushdown", "Extensión de tríceps en polea", "IS", "triceps", "", "polea", "P", "codo", 0, 0, 0,
     ["Codos pegados al cuerpo.", "Empuja la barra hacia abajo.", "Sube lento."], None),
    ("extension-triceps-cuerda", "Triceps_Pushdown_-_Rope_Attachment", "Extensión de tríceps con cuerda", "IS", "triceps", "", "polea", "P", "codo", 0, 0, 0,
     ["Cuerda en polea alta.", "Empuja abajo separando las puntas.", "Sube lento."], None),
    ("extension-triceps-sobre-cabeza", "Standing_Dumbbell_Triceps_Extension", "Extensión de tríceps sobre la cabeza", "IS", "triceps", "", "manc", "P", "codo hombro", 0, 0, 0,
     ["Mancuerna con ambas manos sobre la cabeza.", "Bájala detrás de la cabeza.", "Extiende los codos."], None),
    ("press-frances", "EZ-Bar_Skullcrusher", "Press francés", "IS", "triceps", "", "barraz banco", "I", "codo", 0, 0, 0,
     ["Acostado, barra sobre la frente con brazos verticales.", "Baja doblando codos.", "Extiende."], None),
    ("patada-triceps", "Tricep_Dumbbell_Kickback", "Patada de tríceps", "IS", "triceps", "", "manc", "P", "", 0, 1, 0,
     ["Torso inclinado, codo pegado.", "Extiende el brazo atrás.", "Vuelve lento."], None),
    ("fondos-banco", "Bench_Dips", "Fondos en banco", "HP", "triceps", "pecho hombro", "banco", "P", "hombro muneca", 1, 0, 0,
     ["Manos en el borde de un banco o silla.", "Baja doblando codos.", "Empuja arriba."], None),
    ("press-cerrado", "Close-Grip_Barbell_Bench_Press", "Press de banca agarre cerrado", "HP", "triceps pecho", "hombro", "barra banco", "I", "muneca", 1, 0, 0,
     ["Manos al ancho de hombros.", "Baja al pecho con codos pegados.", "Empuja."], None),
    ("flexiones-diamante", "Push-Ups_-_Close_Triceps_Position", "Flexiones cerradas", "HP", "triceps pecho", "", "cuerpo", "I", "muneca", 1, 0, 0,
     ["Manos juntas bajo el pecho.", "Baja con codos pegados.", "Empuja."], None),
    ("extension-triceps-banda", "Band_Skull_Crusher", "Extensión de tríceps con banda", "IS", "triceps", "", "banda", "P", "", 0, 0, 0,
     ["Banda anclada atrás.", "Extiende los codos.", "Vuelve lento."], None),
    ("curl-muneca", "Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench", "Curl de muñeca", "IS", "antebrazo", "", "manc banco", "P", "muneca", 0, 0, 0,
     ["Antebrazos apoyados, muñecas fuera del banco.", "Sube la mancuerna con la muñeca.", "Baja lento."], None),

    # ---------------- Core ----------------
    ("plancha", "Plank", "Plancha", "CO", "abdomen", "hombro gluteo", "cuerpo", "P", "", 0, 0, 1,
     ["Antebrazos y puntas de pies en el piso.", "Cuerpo recto.", "Sostén apretando abdomen."], None),
    ("plancha-lateral", "Side_Bridge", "Plancha lateral", "CO", "abdomen", "gluteo", "cuerpo", "P", "hombro", 0, 1, 1,
     ["De lado sobre un antebrazo.", "Eleva la cadera en línea recta.", "Sostén."], None),
    ("crunch", "Crunches", "Crunch abdominal", "CO", "abdomen", "", "cuerpo", "P", "cuello", 0, 0, 0,
     ["Acostado con rodillas dobladas.", "Eleva los hombros del piso.", "Baja lento."], None),
    ("bicho-muerto", "Dead_Bug", "Bicho muerto (dead bug)", "CO", "abdomen", "", "cuerpo", "P", "", 0, 0, 0,
     ["Boca arriba, brazos y rodillas arriba.", "Extiende brazo y pierna opuestos sin arquear la espalda.", "Vuelve y alterna."], "Muy seguro para la espalda baja."),
    ("pallof", "Pallof_Press", "Press Pallof", "CO", "abdomen", "", "polea", "P", "", 0, 1, 0,
     ["De lado a la polea, manija al pecho.", "Empuja al frente sin dejar que te gire.", "Vuelve."], None),
    ("pallof-banda", None, "Press Pallof con banda", "CO", "abdomen", "", "banda", "P", "", 0, 1, 0,
     ["Banda anclada a un costado.", "Empuja al frente resistiendo el giro.", "Vuelve."], None),
    ("crunch-polea", "Cable_Crunch", "Crunch en polea", "CO", "abdomen", "", "polea", "I", "lumbar", 0, 0, 0,
     ["Arrodillado, cuerda junto a la cabeza.", "Flexiona el tronco hacia abajo.", "Vuelve lento."], None),
    ("elevacion-piernas-colgado", "Hanging_Leg_Raise", "Elevación de piernas colgado", "CO", "abdomen", "", "dominadas", "I", "hombro lumbar", 0, 0, 0,
     ["Cuelga de la barra.", "Sube las piernas sin balancearte.", "Baja lento."], None),
    ("elevacion-piernas-banco", "Flat_Bench_Lying_Leg_Raise", "Elevación de piernas acostado", "CO", "abdomen", "", "cuerpo", "P", "lumbar", 0, 0, 0,
     ["Acostado, manos bajo la cadera.", "Sube las piernas rectas.", "Baja sin tocar el piso."], None),
    ("crunch-inverso", "Reverse_Crunch", "Crunch inverso", "CO", "abdomen", "", "cuerpo", "P", "", 0, 0, 0,
     ["Acostado, rodillas dobladas arriba.", "Lleva las rodillas al pecho despegando la cadera.", "Baja lento."], None),
    ("giro-ruso", "Russian_Twist", "Giro ruso", "CO", "abdomen", "", "cuerpo", "P", "lumbar", 0, 0, 0,
     ["Sentado con el torso inclinado atrás.", "Gira el torso de lado a lado.", "Mantén el abdomen firme."], None),
    ("escaladores", "Mountain_Climbers", "Escaladores", "CO", "abdomen cardio", "hombro cuad", "cuerpo", "P", "muneca", 0, 0, 1,
     ["Posición de flexión.", "Lleva rodillas al pecho alternando rápido.", "Mantén la cadera baja."], None),
    ("rueda-abdominal", "Ab_Roller", "Rueda abdominal", "CO", "abdomen", "hombro", "otro", "I", "lumbar", 0, 0, 0,
     ["De rodillas con la rueda.", "Rueda al frente sin arquear la espalda.", "Vuelve con el abdomen."], None),
    ("lenador-polea", "Standing_Cable_Wood_Chop", "Leñador en polea", "CO", "abdomen", "hombro", "polea", "P", "lumbar", 0, 1, 0,
     ["Polea alta a un costado.", "Tira en diagonal hacia la cadera contraria.", "Vuelve lento."], None),
    ("paseo-granjero", None, "Paseo del granjero", "CA", "antebrazo trapecio abdomen", "gluteo", "manc", "P", "", 1, 0, 1,
     ["Una pesa pesada en cada mano.", "Camina erguido con pasos cortos.", "Mantén hombros atrás y abdomen firme."], None),

    # ---------------- Cardio ----------------
    ("bici-estatica", "Bicycling_Stationary", "Bicicleta", "CD", "cardio", "cuad", "bici", "P", "", 0, 0, 1,
     ["Ajusta el asiento a la altura de la cadera.", "Pedalea a ritmo constante.", "Puedes conversar sin ahogarte (zona suave)."], None),
    ("caminadora", "Walking_Treadmill", "Caminata en caminadora", "CD", "cardio", "", "cinta", "P", "", 0, 0, 1,
     ["Camina a paso ligero.", "Usa inclinación si quieres más intensidad.", "Mantén la postura erguida."], None),
    ("trote", "Jogging_Treadmill", "Trote", "CD", "cardio", "cuad pantorrilla", "cinta", "P", "rodilla tobillo", 0, 0, 1,
     ["Trote suave.", "Pisada ligera.", "Respira de forma constante."], None),
    ("remo-ergometro", "Rowing_Stationary", "Remo ergómetro", "CD", "cardio", "esp_media cuad", "maquina", "P", "lumbar", 0, 0, 1,
     ["Empuja con las piernas, luego tira con los brazos.", "Vuelve en orden inverso.", "Ritmo constante."], None),
    ("eliptica", "Elliptical_Trainer", "Elíptica", "CD", "cardio", "", "maquina", "P", "", 0, 0, 1,
     ["Sube y toma las manijas.", "Movimiento fluido.", "Ajusta la resistencia."], "Bajo impacto para las rodillas."),
    ("saltar-cuerda", "Rope_Jumping", "Saltar la cuerda", "CD", "cardio", "pantorrilla", "otro", "P", "tobillo rodilla", 0, 0, 1,
     ["Saltos bajos sobre las puntas.", "Gira la cuerda con las muñecas.", "Mantén un ritmo cómodo."], None),
    ("caminata", None, "Caminata rápida", "CD", "cardio", "", "cuerpo", "P", "", 0, 0, 1,
     ["Camina a paso rápido.", "Brazos acompañando.", "Puedes hablar pero no cantar."], None),
    ("jumping-jacks", "Star_Jump", "Saltos de tijera", "CD", "cardio", "", "cuerpo", "P", "rodilla tobillo", 0, 0, 1,
     ["Salta abriendo piernas y brazos.", "Vuelve a cerrar.", "Ritmo constante."], None),
    ("escaladora", "Stairmaster", "Escaladora", "CD", "cardio", "gluteo cuad", "maquina", "P", "rodilla", 0, 0, 1,
     ["Sube escalones a ritmo constante.", "No te cuelgues de las manijas.", "Postura erguida."], None),
]
